### ISSUE TITLE
Adding float support

### ISSUE THREAD

**Issue by WickedShell** [ztellman/primitive-math#1]
I've been using primitive-math for awhile now and found it quite helpful inside the hot loops in my code, but recently came across the need for floating point support, manipulation due to working with some graphics libraries that have to communicate with the GPU. Would a PR adding support for float (adding at a minimum support for eq gt neq and other comparisons) be of interest and useful, or are floats intentionally being held out?

**Comment by ztellman** [comment]
I don't use floats because floating point values tend to get coerced to doubles in Clojure code.  It's easy enough to just add methods to `Primitives.java`, though, so I'd be happy to accept pull requests that add 32-bit versions.

**Comment by WickedShell** [comment]
Yeah I've had the same problem in the past, and in general thats why I've avoided the floats till now. I submitted #2 with floats adde As I mentioned there I'm not sure I have the test setup correctly.

**Comment by WickedShell** [comment]
Closing as #2 addresses it.
