### ISSUE TITLE
Still relevant/difference with :warn-on-boxed?

### ISSUE THREAD

**Issue by didibus** [ztellman/primitive-math#5]
Since Clojure 1.7, they added: (set! *unchecked-math* :warn-on-boxed) to warn you of unchecked math. I was curious to know if that renders primitive-math mostly irrelevant, or if there are still situations where it can provide better value.

Thanks.

**Comment by ztellman** [comment]
It certainly renders it less useful, but there are a few benefits:

* boxed arithmetic is a compiler error, not just a warning
* `*unchecked-math*` only warns on arithmetic operations, while primitive-math does the same for comparison operators, boolean operators, etc.
* primitive-math provides coercion between different primitive types

With that said, I think most people are probably fine just using what Clojure provides out of the box.

**Comment by didibus** [comment]
That answers my question, thanks.
